version: "3.8"
services:
  keycloak:
    image: forevigt/instruweb:latest
    container_name: keycloak
    environment:
      KEYCLOAK_FRONTEND_URL: "http://localhost:8484"
    ports:
      - "8484:8484"
    networks:
      - backend

  mariadb:
    image: forevigt/mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - backend

networks:
  backend:
    driver: bridge
