name: Build Docker

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      keycloak:
        image: forevigt/instruweb:latest
        ports:
          - 8484:8484
      mariadb:
        image: forevigt/mariadb:latest
        ports:
          - 3306:3306
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Build Docker
        run: docker build -f src/main/docker/Dockerfile.jvm -t forevigt/quarkus .